### PR TITLE
Simpler update to Mit and vignette

### PR DESCRIPTION
**Pull request by austinwpearce**
- corrected description of b parameter
- add y_intercept to output table (for comparing to y_intercept of LP and QP)
- corrected XY order of STV and RY in boot_mitscherlich
- added set.seed to bootstrapping section of vignette
- added na.rm = TRUE on quantile calc

### CODE REVIEW

**Comment by adriancorrendo** [comment]
Thanks, Austin for putting this together.

Just give some time to check the x_intercept thing and "b" or "-b"...it looks like a great catch but I just want to make sure we are not missing something.

About the y-intercept, I like it. It looks a great option when the x variable is nutrient rate. However, in the case of STV, y-intercept would not have much interpretation, right? cause the RY with STV=0 should be expected to be zero (or very close), unless it may serve for an indirect indicator of "mineralization" during the season, especially N. The problem is that won't serve much for non-mobile nutrients that we cannot (or shouldn't) transform ppm to kg (like P).

Best,

ADRIAN

**Comment by austinwpearce** [comment]
Visual example of how the b parameter functions in the Mit formulas
$y = a(1 - exp(-c(x+b)))$
mit

**About Y-intercept**
> in the case of STV, y-intercept would not have much interpretation, right? cause the RY with STV=0 should be expected to be zero (or very close)

_In my reply, I admit I'm thinking more about less mobile nutrients (P, K, etc)_

I agree that the interpretation of relative yield begins to break down as STV approaches zero. (Relative metrics in general carry interpretation challenges)
For example, 
- intercept of 80% at zero would suggest 80% of maximum attainable yield can be achieved even when there is absolutely no measurable soil nutrient in the sampled soil depth.
- an intercept of 0% RY would mean that the yield of the fertilized treatment was *infinity* times higher than the control yield without fertilizer.
- a negative intercept would technically mean that either the control or treatment resulted in negative yields (impossible)
  - however, a negative intercept may be acceptable for other reasons (below)

Some have argued that RY should equal 0 when STV equals zero (Steinfurth el al 2022). But I think this misses some counter-arguments:
- researchers don't usually have data at the extremely low soil test values to prove that RY should be near 0%.
  - they could ignore the Y-intercept output as it is like extrapolation
  - even when they do work in soils of <1-2 ppm, the plants could find other ways of getting nutrients (go deeper; see next point)
- **RY is specific to the sampling depth of the soil**
  - for example, STV ~ 0 but only in the top 6 inches sampled, so RY could still equal 20%, for example, because there were nutrients below 6 inches
- a negative RY intercept may be acceptable and interpreted as the soil test value at which yield went to zero because of some other limiting factor/nutrient besides the nutrient of interest
- The RY intercept can be used as a validation method for choosing a model
  - For example, if model 1 produced Y-intercept of 80% RY and model 2 produced Y-intercept of 10% RY, then the researcher can decide if model 2 would better represent their ideal response curve.

The LP and QP functions report the Y-intercept which is why I was adding it to `mitscherlich()`.
Currently we do not restrict the exponential model from having negative intercepts or relatively high intercepts. The researcher can decide if the interpretation is useful.

**Comment by adriancorrendo** [comment]
Austin, 

your response simply rocks it!

Straightforward and simple to follow. 

Thank you for saving me a considerable amount of time.

Definitely a pleasure to work with you!

Cheers,

ADRIAN

**Review by adriancorrendo — APPROVED** [review]
let's approve it!

**Pull request merged**
